apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "*/1 * * * *"    # Cron schedule, here set to run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-nginx
            image: fluentd
            args:
            - /bin/sh
            - -c
            - echo "Hello, World2!"    # Example command
          restartPolicy: OnFailure
