apiVersion: v1
kind: Namespace
metadata:
  name: cyberco

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cyberco
  name: cache-db
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:buster
        ports:
        - containerPort: 6379